### PR TITLE
Prebid.js - Update bid Response to use actual creativeID

### PR DESCRIPTION
**Pull request by sj1815**
## Type of change

- [ ] Bugfix
- [x] Feature
- [ ] New bidder adapter   
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes

- [ ] Does this change affect user-facing APIs or examples documented on http://prebid.org?
- [ ] Other

## Description of change

Update bidResponse to use actual creativeID of an ad in admarkup
https://kargo1.atlassian.net/browse/KRKPD-928

### CODE REVIEW

**Review by juliangan07 — CHANGES_REQUESTED** [review]
Changes looks good, can you also update the `spec` to cover this change; Prebidjs requires it as well.

**Review by njflynn — DISMISSED** [review]
Change is good. As per Julians comment, we need to update spec also

**Comment by sj1815** [comment]
> Changes looks good, can you also update the `spec` to cover this change; Prebidjs requires it as well.

Added changes to spec, but having trouble running tests via `gulp test` so trying to see if I can verify the changes work. 
Update: Forked Repo was out of sync with origin. Rebasing seems to have fixed the issue.

**Review by juliangan07 — APPROVED** [review]

**Review by fionasequeira — APPROVED** [review]

**Review by ssadman22 — APPROVED** [review]
Looks good!

**Comment by nickllerandi** [comment]
Hey @sj1815 it looks like the Prebid reviewer is trying to get these tests resolved. I'm seeing just the 1 test fail on my end as well. 
image

**Comment by sj1815** [comment]
@nickllerandi Yeah just noticed it. Will take a look.

**Pull request merged**
